version: '3.3'
services:
  app:
    build: .
    image: jack
    depends_on:
      - redis
      - mysql
    ports:
    - "8060:8060"
  redis:
    image: "library/redis:alpine"
  mysql:
    image: mysql:5.7
    ports:
      - "3307:3306"
    command: [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
        '--default-time-zone=+8:00'
    ]
    environment:
      MYSQL_DATABASE: J-API
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'
    restart: always
